### PR TITLE
kernel: Add 4.19.10 config for x86

### LINKED ISSUE #287: Bump x86 to 4.19.x

### PR DESCRIPTION
**Pull request by sboeuf**
We want to make sure Kata runs on latest stable kernels so that it
benefits from the latest features.

For instance, in case of Kata relying on NEMU hypervisor, the recent
kernel patches reworking the way timer calibration is handled are
solving some boot latency issues.

Fixes #287

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
The CI is currently building and testing this kernel, I recommend do this in  steps: 

1. first add the new config.

2. In the runtime respository bump the kernel verrsion.

3. Remove/deprecate this kernel.

**Comment by sboeuf** [comment]
@jcvenegas thanks for the advise here. Will do!

**Comment by sboeuf** [comment]
@jcvenegas PR updated! It simply adds the new config for now.

**Comment by jodh-intel** [comment]
lgtm

/test

**Comment by jodh-intel** [comment]
Ping @kata-containers/kernel.

**Comment by bergwolf** [comment]
LGTM! 4.19 is [the latest long term stable kernel](https://lwn.net/Articles/769110/) so it makes sense to move to it for most kata users.

**Comment by sboeuf** [comment]
@bergwolf I agree that's a good thing 4.19 is now the new LTS, but we might still want to follow the latest stable to make sure Kata is always up to date and support latest kernel features.

**Comment by bergwolf** [comment]
@sboeuf Sure, I agree.

**Pull request merged**
