### PR TITLE
packaging : add support for s390x

### LINKED ISSUE #176: allow kernel to build on Z

### PR DESCRIPTION
**Pull request by ydjainopensource**
Fixes #176

Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
+1 to @grahamwhaley's comments.

lgtm

btw - if you have any thoughts on the following, please do comment :smile::

- #8 
- #55 
- #56 
- #78

**Comment by ydjainopensource** [comment]
@grahamwhaley @jodh-intel I have copied this from [linux kit](https://github.com/linuxkit/linuxkit/blob/master/kernel/config-4.14.x-s390x). I just added a comment to disable CONFIG_SERIAL_8250. As I couldn't see this enabled in my own s390x kernel.

As for the CI, this is required for it to work.

Again @jodh-intel , i will take a look at those issues and will comment if I have anything to add. Thanks a lot for letting me know about them.

**Comment by jodh-intel** [comment]
Hi @ydjainopensource, @grahamwhaley - linuxkit seems to have the same license as the Kata project. IANAL but should we not credit the linuxkit authors explicitly here?

@ydjainopensource - Once we've ticked the boxes above, it would be really useful if you could specify all these details (including the commit version for this file) in your commit message.

**Comment by jodh-intel** [comment]
Oh - one more thing @ydjainopensource - you need to bump the version file. If you look at the CI failure:

```
Check Changes in kernel
kernel/build-kernel.sh
kernel/configs/s390_kata_kvm_4.14.x
Kernel directory has changes check kernel/kata_config_version changed
ERROR: Please bump version in kernel/kata_config_version
```

**Comment by jodh-intel** [comment]
Hi @ydjainopensource - please could you add the details to the commit though? :)

**Comment by ydjainopensource** [comment]
@jodh-intel done!

**Comment by grahamwhaley** [comment]
IANAL either :-) The license query is around the kernel config file I guess. I've never seen anybody copyright a kernel config file. It's not exactly 'code', and it will have originated out of the kernel, well Kconfig tool, originally - so in theory you might have to track back what license files generated by Kconfig come under....
Ultimately, as it is a generated file, I don't think we can place a comment in the file itself - so I'm happy for us to confirm the attribution here by pasting a link to where the original file came from.

**Comment by grahamwhaley** [comment]
And then I see @ydjainopensource put in a comment - fine by me :-)

**Comment by jodh-intel** [comment]
Thanks @ydjainopensource!

lgtm

**Comment by ydjainopensource** [comment]
@grahamwhaley I removed the autogenerated comment and added mine. I did this as I have later added a line so its not completely autogenerated now. Should I keep the line?

**Comment by grahamwhaley** [comment]
@ydjainopensource sure, keep the line. I don't think it will break anything. thx

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
