### PR TITLE
pkg: Add bash completion

### LINKED ISSUE #59: Package bash completion code
Once https://github.com/kata-containers/runtime/pull/378 lands, we'll need to update:

- https://github.com/kata-containers/packaging/blob/master/runtime/kata-runtime.spec-template 

... by adding in code like we used to have in the Clear Containers packaging repo to handle the bash completion file:

- https://github.com/clearcontainers/packaging/blob/master/runtime/cc-runtime.spec-template

/cc @raravena80.

### PR DESCRIPTION
**Pull request by raravena80**
Fixes #59 

These are the bits for bash completion in the packaging repo.

Pending https://github.com/kata-containers/runtime/pull/378

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks @raravena80!

lgtm

**Comment by jcvenegas** [comment]
Thank you ! lgtm
The CI got a timeout I will increase the time, and merge it if it pass.

**Comment by jcvenegas** [comment]
due to #72 I tested manually, I got the following errors: 
```
[  140s] + make DESTTARGET=/home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/bin/kata-runtime DESTCONFIG=/home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/defaults/kata-containers/configuration.toml SCRIPTS_DIR=/home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/bin BASH_COMPLETIONSDIR=/home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion/completions/kata-runtime QEMUPATH=/usr/bin/qemu-lite-system-x86_64 install
[  140s] kata-runtime - version 1.0.0 (commit d7beeaeaed67ec15212a4f87c8383765dbaf88fe)
[  140s] 
[  140s] • architecture:
[  140s] 	Host: x86_64
[  140s] 	golang: amd64
[  140s] 	Build: amd64
[  140s] 
[  140s] • golang:
[  140s] 	go version go1.10.2 linux/amd64
[  140s] 
[  140s] • Summary:
[  140s] 
[  140s] 	binary install path (DESTTARGET)      : /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/bin/kata-runtime
[  140s] 	config install path (DESTCONFIG)      : /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/defaults/kata-containers/configuration.toml
[  140s] 	alternate config path (DESTSYSCONFIG) : /etc/kata-containers/configuration.toml
[  140s] 	hypervisor path (QEMUPATH)            : /usr/bin/qemu-lite-system-x86_64
[  140s] 	assets path (PKGDATADIR)              : /usr/share/kata-containers
[  140s] 	proxy+shim path (PKGLIBEXECDIR)       : /usr/libexec/kata-containers
[  140s] 
[  140s]      INSTALL install-scripts
[  140s]      INSTALL install
[  140s]      INSTALL install
[  140s] + sed -i -e '/^initrd =/d' /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/defaults/kata-containers/configuration.toml
[  140s] + /usr/lib/rpm/check-buildroot
[  140s] + /usr/lib/rpm/redhat/brp-ldconfig
[  140s] /sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such file or directory
[  140s] + /usr/lib/rpm/brp-compress
[  140s] + /usr/lib/rpm/brp-strip /usr/bin/strip
[  141s] + /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
[  141s] + /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
[  141s] + /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
[  141s] + /usr/lib/rpm/brp-python-hardlink
[  141s] + /usr/lib/rpm/redhat/brp-mangle-shebangs '' ''
[  141s] *** WARNING: ./usr/share/defaults/kata-containers/configuration.toml is executable but has empty or no shebang, removing executable bit
[  141s] Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.w9e1jj
[  141s] + umask 022
[  141s] + cd /home/abuild/rpmbuild/BUILD
[  141s] + cd kata-runtime-1.0.0+git.086d197
[  141s] + export http_proxy=http://127.0.0.1:9/
[  141s] + http_proxy=http://127.0.0.1:9/
[  141s] + export https_proxy=http://127.0.0.1:9/
[  141s] + https_proxy=http://127.0.0.1:9/
[  141s] + export no_proxy=localhost
[  141s] + no_proxy=localhost
[  141s] + exit 0
[  141s] Processing files: kata-runtime-1.0.0+git.086d197-42.1.x86_64
[  141s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion
[  141s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion/completions
[  141s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion/completions/kata-runtime
[  141s] 
[  141s] 
[  141s] RPM build errors:
[  141s]     File not found: /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion
[  141s]     File not found: /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion/completions
[  141s]     File not found: /home/abuild/rpmbuild/BUILDROOT/kata-runtime-1.0.0+git.086d197-42.1.x86_64/usr/share/bash-completion/completions/kata-runtime
[  141s] 
[  141s] cloud126 failed "build kata-runtime.spec" at Thu Jun 14 15:59:42 UTC 2018.
```

**Comment by raravena80** [comment]
@jcvenegas I was curious on how the files from `<kata-runtime-repo>/data/completions/bash/kata-runtime` would get to `<buildir>/usr/share/bash-completion/completions/kata-runtime`

**Comment by jcvenegas** [comment]
@raravena80 your changes should work, I am trying again now.

**Comment by jcvenegas** [comment]
@raravena80 I see, the packaging scripts currently point to create packages based in  kata1.0 the bash-completition was added after the release.

**Pull request merged**
