### PR TITLE
config: remove CONFIG_REFCOUNT_FULL in config.base for arm

### PR DESCRIPTION
**Pull request by jongwu**
CONFIG_REFCOUN_FULL is gone since v5.5, so remove it here as
kernel for virtio-fs base on v5.6.

Fixes: #1168
Signed-off-by: Jianyong.Wu <jianyong.wu@arm.com>

@devimc  @jodh-intel

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Comment by fidencio** [comment]
Sorry about prematurely running `/test`.
Our DCO check is failing because of:

```
  3047df809ea237bbd68e3d6e1819c42592e97452    Expected "Jianyong Wu <jianyong.wu@arm.com>", but got "Jianyong.Wu <jianyong.wu@arm.com>".
```

**Review by fidencio — APPROVED** [review]
lgtm, @jongwu, thanks!

Please, check the DCO issue in order to move forward with the PR.

**Comment by jongwu** [comment]
Thanks @fidencio, having reposted it. this PR has merged to kata-container-2.0

**Comment by fidencio** [comment]
> Thanks @fidencio, having reposted it. this commit has merged to kata-container-2.0

If the exactly same commit was merged in 2.0, we have a discrepancy in our scripts.
@jodh-intel, are you aware of something different in 2.0 and this branch about the DCO checks?

**Comment by jongwu** [comment]
sorry @fidencio -, I make mistake, this PR has not posted to kata-2.0. It's the [PR](https://github.com/kata-containers/runtime/pull/3028) has merged into kata-2.0.

**Comment by fidencio** [comment]
> sorry @fidencio -, I make mistake, this PR has not posted to kata-2.0. It's the [PR](https://github.com/kata-containers/runtime/pull/3028) has merged into kata-2.0.

Okay, no problem. :-). Thanks!

**Review by devimc — APPROVED** [review]
thanks @jongwu - lgtm

**Comment by jongwu** [comment]
Hello @jodh-intel @devimc - need test for this.

**Comment by amshinde** [comment]
@jongwu Need a bump in kata_config_version here

**Comment by jongwu** [comment]
thanks @amshinde , done.

**Review by jodh-intel — APPROVED** [review]

**Comment by jongwu** [comment]
Hi @lifupan @amshinde,  can you help trigger the tests? thanks.

**Comment by jongwu** [comment]
hello @jodh-intel @devimc , it seems the CI is broken as it can't be triggered.

**Comment by devimc** [comment]
@jongwu can you rebase and try again ?

**Comment by jodh-intel** [comment]
@devimc ^ looks like the snap build isn't triggering ;(

**Comment by devimc** [comment]
@jodh-intel you can't trigger github actions using comments :sweat_smile:

**Comment by devimc** [comment]
please ignore the snap CI, I still need to backport a patch to fix yq

**Comment by jodh-intel** [comment]
@devimc - Doh! ;) We need to remove the entry from https://github.com/kata-containers/community/wiki/Controlling-the-CI.

**Comment by jongwu** [comment]
hello @jodh-intel @devimc , this PR blocked by CI for a long time. Is there any process?

**Comment by jodh-intel** [comment]
@jongwu - I've restarted the failing CI's, so ... :crossed_fingers: it works this time... :smile:

/AzurePipelines run

**Comment by jodh-intel** [comment]
@jongwu - the static checks are failing:

```
ERROR: Required SPDX license header check ('SPDX-License-Identifier: Apache-2.0') failed for the following files:

kernel/configs/fragments/arm64/acpi.conf
kernel/configs/fragments/arm64/base.conf
```

You can either add that header, or you might want to raise a 1.x PR on the tests repo to make the static checker ignore files below `kernel/configs/`. We already did that for 2.x so you could raise a PR very similar to:

- https://github.com/kata-containers/tests/pull/2964

**Comment by jongwu** [comment]
thanks @jodh-intel -, I will raise a PR to fix it.

**Comment by jongwu** [comment]
hello @jodh-intel  @devimc, any comments?

**Review by likebreath — APPROVED** [review]

**Pull request merged**
