### PR TITLE
kernel: Disable CONFIG_IPV6_SIT

### LINKED ISSUE #171: kernel config: why CONFIG_IPV6_SIT=y?
Currently each guest would always have a link/sit interface inside. Any reason we would always want that one? @devimc @sboeuf @WeiZhang555 @amshinde (not sure who to @, so just copying a few random ppl :).

### PR DESCRIPTION
**Pull request by amshinde**
This is not required by default.
Fixes #171

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@devimc done

**Comment by marcov** [comment]
hi @amshinde, can you also update the configs file  for arm64 and s390?

**Comment by devimc** [comment]
@nitkon @Weichen81  do we need this in ppc and arm ?

**Comment by devimc** [comment]
thanks @amshinde

**Comment by Weichen81** [comment]
@devimc No, we don't need it either. I will update the kernel config for Arm64

**Comment by jcvenegas** [comment]
lgtm

**Comment by amshinde** [comment]
@nitkon Can you update the kernel config for powerpc if this is not required?

**Pull request merged**
