### PR TITLE
static-build: build the real static binary for clh - port to statble-1.11

### PR DESCRIPTION
**Pull request by likebreath**
This patch reuses the 'dev_cli.sh' from cloud-hypervisor repo to build a
static binary of clh without creating our own docker image nor
installing extra dependencies.

Fixes: #1033

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@egernst @jcvenegas Let's try to depend-on this PR and see whether it fixes the building error on clh for releasing stable-1.11. 

From my local experiments, the `dev_cli.sh` now is able to build clh v0.7.0. So it looks promising. Thanks for the fix from Rob.

**Comment by egernst** [comment]
testing now on https://github.com/kata-containers/runtime/pull/2927

**Review by devimc — APPROVED** [review]

**Review by amshinde — APPROVED** [review]

**Comment by egernst** [comment]
I see the following failure:
```
10:39:40 not ok 2 initContainer with shared volume
10:39:40 # (in test file k8s-shared-volume.bats, line 44)
10:39:40 #   `kubectl exec "$pod_name" -c "$last_container" -- sh -c "$cmd"' failed
10:39:40 # INFO: k8s configured to use runtimeclass
```

Many other tests succeeded though, so I think we're okay with merging this, since the CLH bits are built correctly.

ACK @jcvenegas @likebreath  ?

**Pull request merged**
