### PR TITLE
kernel: enable zone device to avoid ci failure

### PR DESCRIPTION
**Pull request by jongwu**
kernel setup fail on arm64 as zone device is not support for the
current kernel.
apply memory-hotremove patch and enable zone device. also disable
ptp_kvm on arm64.

Fixes: #1113
Change-Id: I60ec9ab74fae22c9c34998bacf4a4046bda92c63
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

@chavafg  @devimc

### CODE REVIEW

**Comment by jongwu** [comment]
thanks @devimc

**Review by jodh-intel — APPROVED** [review]
Thanks @jongwu.

lgtm

**Comment by chavafg** [comment]
@jongwu please bump the kernel config version:
```
05:10:21 Kernel directory has changes check kernel/kata_config_version changed
05:10:21 ERROR: Please bump version in kernel/kata_config_version
05:10:21 Makefile:24: recipe for target 'test' failed
```

**Comment by devimc** [comment]
@jongwu thanks, this PR needs a rebase

**Comment by jongwu** [comment]
thanks @devimc, done.

**Pull request merged**
