### PR TITLE
kernel: Add 4.19.10 config for powerpc

### PR DESCRIPTION
**Pull request by nitkon**
We want to make sure Kata runs on latest stable kernels so that it
benefits from the latest features.

Fixes: #358

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by nitkon** [comment]
Ping for review...  @kata-containers/packaging 
@jodh-intel : A couple of modules not needed?

**Comment by devimc** [comment]
@nitkon 

CONFIG_OCXL=m
CONFIG_CXLFLASH=m

kata doesn't support modules

**Comment by nitkon** [comment]
Good to merge? @devimc

**Pull request merged**
