### PR TITLE
tag_repos: Make sure osbuilder is updated.

### PR DESCRIPTION
**Pull request by jcvenegas**
Make sure the osbuilder VERSION file is updated before tag

Also, sort repos alphabetically.

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
depends on https://github.com/kata-containers/osbuilder/pull/119

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
The CI is failing. Looks like we might need to install `make` in `.ci/setup.sh`:

```
+ make test
.ci/jenkins_job_build.sh: line 122: make: command not found
```

**Comment by jcvenegas** [comment]
@jodh-intel  @grahamwhaley  @devimc  ready to merge.

**Comment by jodh-intel** [comment]
Still...

lgtm

**Pull request merged**
