### PR TITLE
kernel: Enable ptp_kvm for 5.4 kernel on arm64.

### PR DESCRIPTION
**Pull request by jongwu**
The enablement of ptp_kvm for arm is under review, see [1].
So we have to apply private patch to enable it in 5.4 kernel.
ptp_kvm can offer the capability of time sync in kata even there
is no network available and higher precision than time sync
service depend on network.

note:
If you want to use this feature on your arm machine, the host kernel
also need apply this patch. we recommend that your host kernel version
is the 5.4, then you can apply this patch smoothly.

[1] https://patchwork.kernel.org/cover/11372743/

Fixes: #997
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

@devimc @grahamwhaley  @Pennyzct

### CODE REVIEW

**Comment by devimc** [comment]
@jongwu  couldn't not apply a patch

```
linux-5.4.15.tar.xz: OK
INFO: Applying patch /tmp/jenkins/workspace/kata-containers-packaging-ubuntu-18-04-snap-PR/go/src/github.com/kata-containers/packaging/kernel/patches//5.4.x/0001-arm-arm64-Provide-a-wrapper-for-SMCCC-1.1-calls.patch
patching file include/linux/arm-smccc.h
INFO: Applying patch /tmp/jenkins/workspace/kata-containers-packaging-ubuntu-18-04-snap-PR/go/src/github.com/kata-containers/packaging/kernel/patches//5.4.x/0003-ptp-arm64-Enable-ptp_kvm-for-arm64.patch
patching file drivers/clocksource/arm_arch_timer.c
patching file drivers/firmware/psci/psci.c
Hunk #1 FAILED at 71.
1 out of 1 hunk FAILED -- saving rejects to file drivers/firmware/psci/psci.c.rej
```

**Comment by jongwu** [comment]
@devimc it's strange as it works in my machine.

**Comment by jongwu** [comment]
@devimc I think that the order of patch applied cause that error, the patch should apply in order of 0001,0002,0003, if 0003 applied before 0002, error will occur.
So, should I squash patch serial to avoid that problem? @jodh-intel @devimc

**Comment by jodh-intel** [comment]
@jongwu, @devimc - I found the problem: https://github.com/kata-containers/packaging/pull/1005.

**Comment by jongwu** [comment]
thanks @jodh-intel

**Comment by jodh-intel** [comment]
Now that https://github.com/kata-containers/packaging/pull/1005 has landed, let's re-run the CI...

/retest

**Comment by jongwu** [comment]
thanks @jodh-intel , need retest as I just bump config version.

**Comment by jongwu** [comment]
@jodh-intel can you help retest it? thanks

**Comment by jongwu** [comment]
hi @jodh-intel @devimc , help retest, thanks!

**Comment by jongwu** [comment]
hi @devimc @jodh-intel , help retest obs ci to see if that's a random error, thanks.

**Comment by grahamwhaley** [comment]
Here is the log. I'll try to kick a rebuild...

```
Project home:katacontainers:ci:x86_64:packaging-PR-998 has failed packages
 kata-containers-image
 | ksm-throttler
 | | linux-container
 | | | proxy
 | | | | qemu-vanilla
 | | | | | runtime
 | | | | | | shim
 % s s s s s s  CentOS_7 x86_64 (building)
 % s s s s s s  Debian_10 x86_64 (building)
 s s % s s s s  Debian_9 x86_64 (building)
 s s % s s s s  Fedora_30 x86_64 (building)
 % s s s s s s  SLE_15_SP1 x86_64 (building)
 s s % s s s s  openSUSE_Leap_15.1 x86_64 (building)
 % s f s s s s  openSUSE_Tumbleweed x86_64 (outdated)
 % s % s s s s  xUbuntu_16.04 x86_64 (building)
 f s % s s s s  xUbuntu_18.04 x86_64 (building)

 Legend:
  . succeeded           
    disabled            
  U unresolvable        
  F failed              
  B broken              
  b blocked             
  % building            
  f finished            
  s scheduled           
  L locked              
  x excluded            
  d dispatching         
```

**Comment by jongwu** [comment]
oh, building for linux-container all failed, is there any detail info to see why that happen? @grahamwhaley

**Comment by grahamwhaley** [comment]
I can't see anything on the Action/azure page - I think it will come down to some OBS stuff - we need to ask @jcvenegas for help I think.
It could be spurious, but let's check this failure first before we try a rebuild.

I'm also not sure why the ubuntu builds don't seem to be triggering....

**Comment by devimc** [comment]
@jongwu 

https://build.opensuse.org/package/show/home:katacontainers:ci:x86_64:packaging-PR-998/linux-container

```
[  119s] + echo 'Patch #1 (0001-arm-arm64-Provide-a-wrapper-for-SMCCC-1.1-calls.patch):'
[  119s] Patch #1 (0001-arm-arm64-Provide-a-wrapper-for-SMCCC-1.1-calls.patch):
[  119s] + /usr/bin/cat /home/abuild/rpmbuild/SOURCES/0001-arm-arm64-Provide-a-wrapper-for-SMCCC-1.1-calls.patch
[  119s] + /usr/bin/patch -p1 --fuzz=0
[  119s] patching file include/linux/arm-smccc.h
[  119s] + echo 'Patch #2 (0003-ptp-arm64-Enable-ptp_kvm-for-arm64.patch):'
[  119s] Patch #2 (0003-ptp-arm64-Enable-ptp_kvm-for-arm64.patch):
[  119s] + /usr/bin/cat /home/abuild/rpmbuild/SOURCES/0003-ptp-arm64-Enable-ptp_kvm-for-arm64.patch
[  119s] + /usr/bin/patch -p1 --fuzz=0
[  119s] patching file drivers/clocksource/arm_arch_timer.c
[  119s] patching file drivers/firmware/psci/psci.c
[  119s] Hunk #1 FAILED at 71.
[  119s] 1 out of 1 hunk FAILED -- saving rejects to file drivers/firmware/psci/psci.c.rej
[  119s] patching file drivers/ptp/Kconfig
[  119s] patching file drivers/ptp/Makefile
[  119s] patching file drivers/ptp/ptp_kvm.h
[  119s] patching file drivers/ptp/ptp_kvm_arm64.c
[  119s] patching file drivers/ptp/ptp_kvm_common.c (renamed from drivers/ptp/ptp_kvm.c)
[  119s] patching file drivers/ptp/ptp_kvm_x86.c
[  119s] patching file include/linux/arm-smccc.h
[  119s] patching file include/linux/clocksource.h
[  119s] patching file include/linux/clocksource_ids.h
[  119s] patching file include/linux/timekeeping.h
[  119s] patching file include/uapi/linux/kvm.h
[  119s] patching file kernel/time/clocksource.c
[  119s] patching file kernel/time/timekeeping.c
[  119s] patching file virt/kvm/arm/arm.c
[  119s] patching file virt/kvm/arm/psci.c
[  119s] error: Bad exit status from /var/tmp/rpm-tmp.UvOSAI (%prep)
```

**Comment by jongwu** [comment]
@devimc @grahamwhaley this patch set should be applied in order. how to avoid that failure, should I squeezing these patch set?

**Comment by jodh-intel** [comment]
This PR is effectively blocked on #1016.

**Comment by devimc** [comment]
@jongwu this PR may need a rebase :smile:

**Comment by jongwu** [comment]
thanks @devimc

**Comment by jongwu** [comment]
hi @devimc @jodh-intel, help trigger snap ci, thanks!

**Pull request merged**
