### PR TITLE
config: enable printk-time for kernel-5.4 for arm64

### PR DESCRIPTION
**Pull request by jongwu**
Open PRINTK_TIME in arm64_kata_kvm_5.4.x to let kernel print timestamp
correctly.

Fixes: #987
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

@devimc  @grahamwhaley  @jodh-intel  @Pennyzct

### CODE REVIEW

**Comment by amshinde** [comment]
I am seeing this unexpected failure on Ubuntu:
```
sudo: kubeadm: command not found
```
Rerunning tests...

**Comment by Pennyzct** [comment]
@grahamwhaley thanks, heh heh I'm already working on that~~~~

**Pull request merged**
