### PR TITLE
kernel: update to 4.19.24 on s390x

### LINKED ISSUE #360: kernel: update to 4.19.24 on s390x
Let's override #340 with this one. 1 stone 2-3 birds.

### PR DESCRIPTION
**Pull request by tuan-hoang1**
Add CONFIG_CFS_BANDWIDTH so CPU hotplug feature works on s390x. Note
that CPU hot-unplug does not work yet due to limitation in qemu s390x.

Remove CONFIG_USB_SUPPORT because s390x doesn't do USB.

Fixes #360

Signed-off-by: Tuan Hoang <tmhoang@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @tuan-hoang1 - thanks for raising. I think it would be helpful if you could split the commit into two separate ones: one for the USB removal and the other for the CFS_BANDWIDTH.

**Comment by tuan-hoang1** [comment]
Updated, thanks @jodh-intel.

**Comment by jodh-intel** [comment]
Thanks @tuan-hoang1. Ideally that USB commit would mention USB in the commit title as the current "kernel: update to 4.19.24 on s390x" is a bit generic.

**Comment by tuan-hoang1** [comment]
Thanks @jodh-intel, I updated it.

**Comment by jodh-intel** [comment]
Ping @kata-containers/packaging.

**Comment by grahamwhaley** [comment]
that 18.04 CI fail looks odd - nothing to do with this PR afaict, but something strange happened in the jenkins script - I'll prod a re-run, but the output looks like:

```
Drop caches
/tmp/jenkins/workspace/kata-containers-packaging-ubuntu-16-04-PR/go/src/github.com/kata-containers/packaging
+ '[' -z '' ']'
+ specific_branch=
+ '[' -z 361 ']'
+ .ci/static-checks.sh github.com/kata-containers/packaging ''
+ command -v kata-runtime
```

I'm not sure that static-checks.sh invocation is quite right... let's see...

**Comment by tuan-hoang1** [comment]
@grahamwhaley I guess you meant 16.04 CI. Yeah it does not relate to this PR.
Speaking of 4.19.25, I checked and there's no change from 4.19.24 on s390x.

**Comment by grahamwhaley** [comment]
Hi @tuan-hoang1 - well, CI line in the status says `jenkins-ci-ubuntu-18-04` :-) That was updated recently from 16.04. Sure, the s390x slave itself is probably still on 16.04, and that is not an issue. I just wanted to check if that 18.04 fail was spurious (even though I believe unrelated to this PR).
So, let's wait for that CI to complete again, and then merge this PR no matter I think.

**Comment by tuan-hoang1** [comment]
@grahamwhaley would you mind mergin this one? I just rebased to master and pushed.

**Comment by grahamwhaley** [comment]
As this only touches s390 files, which does not CI on this repo, no need to test. It also brings the s390 kernel up to date with our 4.19 default. force merging...

**Pull request merged**
