### PR TITLE
# Kata Containers 1.12.2

### PR DESCRIPTION
**Pull request by bergwolf**
- [backport] snap: tag yq version

b6c1336 snap: tag yq version

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Review by egernst — APPROVED** [review]

**Comment by fidencio** [comment]
The @kata-containers/architecture-committee has decided that there'll be no more releases related to the stable-1.12 branch, thus, let's close this PR.

**Pull request closed without merging**
