### PR TITLE
Firecracker support: Add support for virtio-mmio

### PR DESCRIPTION
**Pull request by mcastelino**
Add support for virtio-mmio. Firecracker uses virtio-mmio.

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @mcastelino - please can you bump the version in `kernel/kata_config_version` as otherwise the CI will fail.
 
Also cc'ing @Pennyzct, @Weichen81, @nitkon and @alicefr as they might need to update their kernel configs too ;)

**Comment by jodh-intel** [comment]
@kata-containers/architecture-committee et al - I've just created @kata-containers/kernel so we have a list of folk involved with guest kernel configurations. This should make it easier to ping all interested parties when new kernel-related PRs are raised.

**Comment by jodh-intel** [comment]
@mcastelino - you still need to increase the value in `kernel/kata_config_version` to allow the CI to run on this PR.

lgtm

**Comment by bergwolf** [comment]
lgtm

**Pull request merged**
