### PR TITLE
Whitelist CONFIG_MEMCG_SWAP_ENABLED

### LINKED ISSUE #1122: Whitelist CONFIG_MEMCG_SWAP_ENABLED for better compatibility with newer kernels
# Description of problem

Kernel 5.8 and onward no longer support CONFIG_MEMCG_SWAP_ENABLED
See https://cateee.net/lkddb/web-lkddb/MEMCG_SWAP_ENABLED.html

For maximum compatibility it should be added to /kernel/configs/fragments/whitelist.conf

### PR DESCRIPTION
**Pull request by skaegi**
See https://cateee.net/lkddb/web-lkddb/MEMCG_SWAP_ENABLED.html
Whitelisting this config item provides compatibility with 5.8+ kernels.

Fixes #1122

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @skaegi

**Comment by devimc** [comment]
btw - The sign-off is missing.

**Comment by skaegi** [comment]
> btw - The sign-off is missing.

Yes -- sigh -- my bad. I tried a force update and added it. See https://github.com/kata-containers/packaging/pull/1123/commits/3d36955c53c2ef7d8c52643d2031015eec4105af

That did not however re-trigger the DCO Check. Is there a way to re-trigger this all?

**Comment by devimc** [comment]
@skaegi same error, ptal https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#general-format

```
Signed-off-by: Contributors Name <contributor@foo.com>
```

**Review by jodh-intel — APPROVED** [review]
Thanks @skaegi.

lgtm

**Comment by jodh-intel** [comment]
@skaegi - Please can you rework the commit message to be something like the following and the `git push -f` to re-trigger the failing DCO check:

```
kernel: Whitelist CONFIG_MEMCG_SWAP_ENABLED

See https://cateee.net/lkddb/web-lkddb/MEMCG_SWAP_ENABLED.html
Whitelisting this config item provides compatibility with 5.8+ kernels.

Fixes: #1122.

Signed-Off-By: Simon Kaegi <simon.kaegi@gmail.com>
```

**Comment by skaegi** [comment]
> Signed-Off-By: Simon Kaegi <simon.kaegi@gmail.com>

Thanks @jodh-intel -- I swear I will never screw this up again ;)

**Review by jodh-intel — COMMENTED** [review]
@skaegi - Please can you update `kernel/kata_config_version` to allow this to be merged?

**Comment by fidencio** [comment]
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

**Pull request closed without merging**
