### PR TITLE
snap: fix build error in launchpad

### LINKED ISSUE #240: could not build snap in launchpad: cpio: command not found
```
[OK] init is installed
[OK] Agent is installed
INFO: Creating /build/kata-containers/parts/image/build/kata-containers-initrd.img based on rootfs at /build/kata-containers/parts/image/build/alpine_rootfs
/build/kata-containers/parts/image/build/initrd-builder/initrd_builder.sh: line 79: cpio: command not found
Skipping build kernel-dump (already ran)
````

### PR DESCRIPTION
**Pull request by devimc**
Add cpio to build-packages list since it's required to create initrd images

fixes #240

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
lgtm

**Comment by sboeuf** [comment]
@jcvenegas PTAL

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
