### PR TITLE
ci: Run all CI test.

### PR DESCRIPTION
**Pull request by jcvenegas**
run all CI test to increase testing coverage on kernel config changes.

Fixes: #346

### CODE REVIEW

**Comment by jcvenegas** [comment]
all the test passed, @devimc  seems that snap failed, @grahamwhaley  I think you hit some issues about yq last week 
```
snapd is not logged in, snap install commands will use sudo
2019-02-21T15:48:23Z INFO Waiting for restart...
yq 2.2.0 from 'mikefarah' installed
Pulling go 
'image' has dependencies that need to be staged: go
Skipping pull go (already ran)
Building go 
Segmentation fault (core dumped)
15:48:34 main [ERRO] Asked to process document index 0 but there are only 0 document(s)
```

**Comment by grahamwhaley** [comment]
that doesn't look like the same `yq` issue I hit. Mine as if you had 'interesting' strings in your yaml then you can blow `yq` (to be fair, you actually afaik blow the base golang yaml library...)
https://github.com/mikefarah/yq/issues/188#issuecomment-463671804
This PR is not changing any YAML I think, so probably not the same thing.

**Comment by devimc** [comment]
@jcvenegas CI is not happy, I think you should rebase your pr

**Pull request merged**
