### PR TITLE
kernel: enable STACKPROTECTOR configs in security.conf

### PR DESCRIPTION
**Pull request by mythi**
As per the comments in security.conf, the intention was to
enable STACKPROTECTOR and STACKPROTECTOR_STRONG.

The current config leaves them unset in the final .config
and also prevents other fragments from overriding the setting.

Set both to =y as indicated in the comments.

Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@jcvenegas Can you take a look why the Packaging CI is failing.

**Comment by mythi** [comment]
v2: I've dropped `CONFIG_STACKPROTECTOR_STRONG=y` because it fails on some distros in OBS.

**Comment by mythi** [comment]
@jcvenegas thanks! OBS is clean now so it's the gcc version I reported earlier.

**Comment by jcvenegas** [comment]
@mythi @egernst about the errors related with SLE,  https://github.com/kata-containers/packaging/pull/662 will bump to SLE12 to SP4 hopefully will provide  a new  enough gcc version.

**Pull request merged**
