### PR TITLE
# Kata Containers 1.13.0-alpha1

### PR DESCRIPTION
**Pull request by bergwolf**
- config: remove CONFIG_REFCOUNT_FULL in config.base for arm
- static-build: Pull the release binary of cloud-hypervisor first
- ci: Fixes for virtiofs stable
- snap: tag yq version

be5c573 config: bump kernel config
533751a kernel/config: enable efi_rtc support for arm64
51c8ff9 static-build: Pull the release binary of cloud-hypervisor first
0dc7fb4 snap: Fix build for virtiofs
0db1700 obs: Fix build for qemu package
7b6986b ci: obs: Fix default branch in tests repository
9eec02e kernel: ACPI: Always build evged for stable kernel
8def37f qemu: Install virtiofs with vanilla qemu.
6da4b5f config: remove CONFIG_REFCOUNT_FULL in config.base for arm
fe95b20 snap: tag yq version

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Review by egernst — APPROVED** [review]

**Comment by fidencio** [comment]
We're closing this one as we'll go directly to the 1.13.0-rc0 one.

**Pull request closed without merging**
