### PR TITLE
obs: Update SLES version for packaging

### LINKED ISSUE #983: update sles version for obs packaging

### PR DESCRIPTION
**Pull request by GabyCT**
Currently for our CI, we have SLES 15 SP1, this PR updates the current obs
version to match with our current testing.

Fixes #983

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@rhafer , I am trying to build the kata containers obs packages for SLES 15 SP1. However, one of the issues that I have at the obs is the following
```
[  119s] kata-containers-image.src: E: invalid-license (Badness: 100000) Artistic-1.0 BSD-3-Clause BSD-3-Clause-Kata BSD-4-Clause-UC GFDL-1.3 GPL-2.0 GPL-2.0+ GPL-3.0 GPL-3.0+ LGPL-2.0 LGPL-2.0+ LGPL-2.1 LGPL-3.0+ MIT MPL-2.0 Public-Domain
[  119s] kata-containers-image.x86_64: E: invalid[  110.201321] serial8250: too much work for irq4
[  119s] -license (Badness: 100000) Artistic-1.0 BSD-3-Clause BSD-3-Clause-Kata BSD-4-Clause-UC GFDL-1.3 GPL-2.0 GPL-2.0+ GPL-3.0 GPL-3.0+ LGPL-2.0 LGPL-2.0+ LGPL-2.1 LGPL-3.0+ MIT MPL-2.0 Public-Domain
[  119s] The specified license string is not recognized. Please refer to
[  119s] https://spdx.org/licenses/ for the list of known licenses and their exact
[  119s] spelling.
[  119s] 
[  119s] (none): E: badness 200000 exceeds threshold 1000, aborting.
[  119s] 2 packages and 0 specfiles checked; 2 errors, 6 warnings.
[  119s] 
[  119s] ### VM INTERACTION START ###
[  122s] [  113.288885] sysrq: SysRq : Power Off
[  122s] [  113.297502] reboot: Power down
[  122s] ### VM INTERACTION END ###
[  122s] 
[  122s] lamb14 failed "build kata-containers-image.spec" at Tue Mar 24 17:52:46 UTC 2020.
```
any idea of how I can fix that? (more details https://build.opensuse.org/package/live_build_log/home:katacontainers:ci:x86_64:packaging-PR-984/kata-containers-image/SLE_15_SP1/x86_64)

**Comment by GabyCT** [comment]
@rhafer , the same error about licenses, I get for the qemu package
```
[  362s] qemu-vanilla.x86_64: E: invalid-license (Badness: 100000) BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1
[  362s] The specified license string is not recognized. Please refer to
[  362s] https://spdx.org/licenses/ for the list of known licenses and their exact
[  362s] spelling.
```
https://build.opensuse.org/package/live_build_log/home:katacontainers:ci:x86_64:packaging-PR-984/qemu-vanilla/SLE_15_SP1/x86_64

The specs for the packages are at https://github.com/kata-containers/packaging/blob/master/obs-packaging/qemu-vanilla/qemu-vanilla.spec-template and https://github.com/kata-containers/packaging/blob/master/obs-packaging/kata-containers-image/kata-containers-image.spec-template

**Comment by rhafer** [comment]
@GabyCT when build for SLE, OBS seems to have some stricter rpmlint checks in place.

AFAICS there is two things that rpmlint is complaining about:
1. If a package contains stuff covered by multiple licenses the indivual licenses in the `License` tag is supposed to be concatenated by either `and` or `or`. So the correct License tag would be:

`License: Artistic-1.0 and BSD-3-Clause  and BSD-3-Clause-Kata and  BSD-4-Clause-UC ...`

2. The licenses `BSD-3-Clause-Kata`  and `Public-Domain` are not valid SPDX License identifiers (as listed on https://spdx.org/licenses/). "Public-Domain" is not really a license, is it. Isn't it more the absense of any license? And regarding "BSD-3-Clause-Kata" I am unsure, is there really anything with Kata specific BSD license? You might wanna use "BSD-3-Clause-Attribution" there.

Note: Alternatively, you could just tone down the severity of the rpmlint check by setting the badness of the "invalid-license" check to some smaller value via local configuration. For that you'd have to add a file `kata-containers-image.rpmlintrc` to the package dir with just this line it it:

```
setBadness('invalid-license', 0)
```

**Comment by grahamwhaley** [comment]
Hmm, /me wonders just where ` BSD-3-Clause-Kata` is coming from.... afaik, all Kata stuff is `Apache 2.0` ... ?
If nobody knows, maybe I'll go hunt that down ...

**Comment by grahamwhaley** [comment]
And I don't know why we'd append `-Kata` either - although, I have some memory that the main BSD license template file does have a place you append the project/company name... that may not apply to the SPDX line though. Needs more looking...

**Comment by GabyCT** [comment]
thanks @rhafer

**Comment by grahamwhaley** [comment]
OK, in the [OBS spec template file](https://github.com/kata-containers/packaging/blob/master/obs-packaging/kata-containers-image/kata-containers-image.spec-template#L4), we have a line:

```
License:        Artistic-1.0 BSD-3-Clause BSD-3-Clause-Kata BSD-4-Clause-UC GFDL-1.3 GPL-2.0 GPL-2.0+ GPL-3.0 GPL-3.0+ LGPL-2.0 LGPL-2.0+ LGPL-2.1 LGPL-3.0+ MIT MPL-2.0 Public-Domain 
```

I'm not sure what ` BSD-3-Clause-Kata` means in this line - Kata is almost completely Apache 2.0, and I'm not sure ` BSD-3-Clause-Kata` makes sense as an SPDX style identifier....

@jcvenegas , do you know/remember where this came from? I don't understand the innards of OBS, but ideally I think we should drop that part of that line. afaict, it should not cause any issues. Please, anybody, if you know or can think of any history of this bit or any issues it might raise dropping it, shout now....

**Comment by jcvenegas** [comment]
@grahamwhaley I dont remember where it comes from, probably was a typo from initial implementation from Eric Cardona long time ago, because we know there is not such a license I feel is fine just to remove it.

**Pull request merged**
