### PR TITLE
kata-deploy: Add qemu-virtiofs wrapper

### PR DESCRIPTION
**Pull request by jcvenegas**
Tarball is missing to provide a wrapper for qemu-virtiofs

Fixes: #756

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
snap ci
```
Build CNI plugins
.ci/install_cni_plugins.sh: line 25: ./build_linux.sh: No such file or directory
Failed at 25: ./build_linux.sh
```

**Comment by jcvenegas** [comment]
https://github.com/kata-containers/packaging/pull/763 include this changes, lets merge the other PR

**Comment by chavafg** [comment]
should we close this?

**Pull request closed without merging**
