### PR TITLE
release: use absolute path for kubeconfig

### PR DESCRIPTION
**Pull request by jcvenegas**
Use absolute path to kubeconfig to allow kubectl use it.

Fixes: #915

### CODE REVIEW

**Comment by devimc** [comment]
snap CI is not happy I guess nothing related to this pr

```
not ok 2 initContainer with shared volume
# (in test file k8s-shared-volume.bats, line 44)
#   `kubectl exec "$pod_name" -c "$last_container" -- sh -c "$cmd"' failed
# INFO: k8s configured to use runtimeclass
# pod/initcontainer-shared-volume created
# pod/initcontainer-shared-volume condition met
# command terminated with exit code 1
# pod "initcontainer-shared-volume" deleted
```

**Comment by jcvenegas** [comment]
https://build.opensuse.org/project/show/home:katacontainers:ci:x86_64:packaging-PR-917 took a long time to publish results, trying again

**Pull request merged**
