### PR TITLE
snap: release 1.5.1

### LINKED ISSUE #367: snap: release 1.5.1

### PR DESCRIPTION
**Pull request by devimc**
release 1.5.1

fixes #367

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
cry-oh (crio) fail on CI :-(

**Comment by jodh-intel** [comment]
:cry:

**Comment by chavafg** [comment]
Seems like the same reported on: https://github.com/kata-containers/tests/issues/1258
restarted the job.

**Comment by jodh-intel** [comment]
@devimc - Following on from https://github.com/kata-containers/packaging/pull/342#issuecomment-467459294, shouldn't we now see a s390x version of the snap on https://snapcraft.io/kata-containers? I'm not seeing it...?

**Comment by devimc** [comment]
@jodh-intel nop, kernel 4.19.x is not part of 1.5.1, see https://github.com/kata-containers/runtime/blob/1.5.1/versions.yaml#L136

**Pull request merged**
