### PR TITLE
kernel: move "enable memory hotremove patch" to right place

### PR DESCRIPTION
**Pull request by jongwu**
I'm sorry to have leaved "the patch" to a wrong place. This commit
corrects it.

Fixes: #1113
Signed-off-by: Jianyong Wu jianyong.wu@arm.com

@devimc  @jodh-intel

### CODE REVIEW

**Comment by jongwu** [comment]
hi @devimc @jodh-intel, please trigger the ARM-test ci to test this PR. Thanks.

**Review by jodh-intel — APPROVED** [review]

**Comment by devimc** [comment]
ERROR: Please bump version in kernel/kata_config_version

**Comment by jongwu** [comment]
thanks @devimc

**Comment by devimc** [comment]
missing < > in the sign-off:  Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

**Comment by jongwu** [comment]
thanks @devimc , DCO check passed!

**Pull request merged**
