### PR TITLE
pkg: qemu-vanilla: organize patches per version.

### PR DESCRIPTION
**Pull request by jcvenegas**
If we apply patches directly to qemu package
this will fail unless we use qemu 4.0 (not yet today).

This patch organize qemu patches per version. For following
PRs we should make scripts aware of this and apply the right
set of patches.

Fixes: #475

### CODE REVIEW

**Comment by jcvenegas** [comment]
@ganeshmaharaj this is needed or this release will have issues to build qemu-vanilla package

**Comment by devimc** [comment]
but... all the patches in `patches/` will be applied either way https://github.com/kata-containers/packaging/blob/master/obs-packaging/scripts/pkglib.sh#L345  :confused:

**Comment by jcvenegas** [comment]
@devimc it is a relative path so depending where is called that function.  If not we would be applying kernel patches to other packages.

**Comment by devimc** [comment]
lgtm, but snap is not happy

```
Building qemu 
fatal: destination path 'qemu' already exists and is not an empty directory.
Failed to run 'override-build': Exit code was 128.
Makefile:47: recipe for target 'snap' failed
make: *** [snap] Error 2
Build step 'Execute shell' marked build as failure
```

**Pull request merged**
