### PR TITLE
kernel: Fix patch ordering

### PR DESCRIPTION
**Pull request by jodh-intel**
Fix the `build-kernel.sh` script to sort patches correctly. Previously,
it relied on `find(1)` for the ordering. However, `find(1)` does not
guarantee any ordering of files within a directory. Since the ordering
could therefore be "random", it was quite possible for patches to be
applied in the wrong order, resulting in conflicts.

Fixes: #1003.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@jodh-intel can you please bump version in `kernel/kata_config_version`

**Comment by jodh-intel** [comment]
@chavafg - done :smile: 

/test

**Pull request merged**
