### PR TITLE
[DNM] Test snap & kernel fragments

### PR DESCRIPTION
**Pull request by devimc**
:worried:

### CODE REVIEW

**Comment by devimc** [comment]
cc @grahamwhaley @ganeshmaharaj

**Comment by grahamwhaley** [comment]
/test
I'm presuming this is a smoke test @devimc , hence the DNM.
The last commit therefore is the interesting one? - and that lgtm - in fact, it looks like that script got simplified by using the `build_kernel.sh` invocation?

**Comment by devimc** [comment]
@grahamwhaley 
> I'm presuming this is a smoke test @devimc , hence the DNM.
yes

> in fact, it looks like that script got simplified by using the build_kernel.sh invocation?
yes, build and install linux kernel will be easier

**Comment by devimc** [comment]
PR rebased

**Pull request closed without merging**
