### PR TITLE
sock: Add mising fix to experimental kernel

### LINKED ISSUE #932: vsock communication sporadically fails
Sometimes, the vsock connection fails because of some race condition in the virtio-vsock guest driver.

### PR DESCRIPTION
**Pull request by jcvenegas**
Cloud hypervisor uses vsock, without this patch CI
for cloud hypervisor is not stable.

Patch information:
```
There was a race condition between bind() and listen() that was hit very
rarely when using Kata Containers and Cloud-Hypervisor. It's been
identified the problem is really coming from the virtio-vsock driver,
which is fixed by those new kernel patches uploaded for each version of
the kernels used by Kata Containers.
```

Fixes #932

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Azure pipelines failed
```
 ---> 463a490e010d
Successfully built 463a490e010d
Successfully tagged obs-kata:latest
Sending meta data...
Server returned an error: HTTP Error 401: Unauthorized
```

**Comment by amshinde** [comment]
@jcvenegas Looks like a candidate for backport, wdyt?

**Comment by likebreath** [comment]
I realized we are creating a new folder with patches for a different version of experimental kernel. It sounds like different versions of kernel are using different patch folders. Do we need to revisit the [patch folder for the old version of experimenta](https://github.com/kata-containers/packaging/tree/master/kernel/patches/virtio-fs-v0.3.x)l and make sure we are not missing other patches, e.g. the ACPI GED?

**Comment by jcvenegas** [comment]
> I realized we are creating a new folder with patches for a different version of experimental kernel. It sounds like different versions of kernel are using different patch folders. Do we need to revisit the [patch folder for the old version of experimenta](https://github.com/kata-containers/packaging/tree/master/kernel/patches/virtio-fs-v0.3.x)l and make sure we are not missing other patches, e.g. the ACPI GED?

I have tried to apply the old commits other patches but others does not apply anymore, I compared with 5.4.x patches and I dont see the patch anymore.

**Comment by jcvenegas** [comment]
OBS is failing I see qemu package for debian is not errors.
```
[ 1065s] dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/qemu-vanilla/usr/bin/virtfs-vanilla-proxy-helper debian/qemu-vanilla/usr/bin/qemu-vanilla-system-x86_64 debian/qemu-vanilla/usr/bin/qemu-vanilla-pr-helper debian/qemu-vanilla/usr/libexec/qemu-vanilla/qemu-bridge-helper were not linked against libgthread-2.0.so.0 (they use none of the library's symbols)
[ 1065s] dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/qemu-vanilla/usr/bin/virtfs-vanilla-proxy-helper debian/qemu-vanilla/usr/bin/qemu-vanilla-system-x86_64 debian/qemu-vanilla/usr/bin/qemu-vanilla-pr-helper debian/qemu-vanilla/usr/libexec/qemu-vanilla/qemu-bridge-helper were not linked against libstdc++.so.6 (they use none of the library's symbols)
[ 1065s]    dh_installdeb
[ 1065s]    dh_gencontrol
[ 1065s] dpkg-gencontrol: warning: Depends field of package qemu-vanilla: unknown substitution variable ${perl:Depends}
[ 1066s]    dh_md5sums
[ 1067s]    dh_builddeb
[ 1067s] dpkg-deb: building package 'qemu-vanilla' in '../qemu-vanilla_4.1.1+git.99c5874a9b-3_amd64.deb'.
[ 1081s]  dpkg-genbuildinfo
[ 1082s]  dpkg-genchanges  >../qemu-vanilla_4.1.1+git.99c5874a9b-3_amd64.changes
[ 1085s] dpkg-genchanges: info: including full source code in upload
[ 1085s]  dpkg-source --after-build BUILD
[ 1086s] dpkg-buildpackage: info: full upload (original source is included)
[ 1086s] ln: failed to create hard link '///usr/src/packages/DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3.dsc': File exists
[ 1086s] ln: failed to create hard link '///usr/src/packages/DEBS/qemu-vanilla_4.1.1+git.99c5874a9b.orig.tar.gz': File exists
[ 1086s] ln: failed to create hard link '///usr/src/packages/DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3.diff.gz': File exists
[ 1086s] Warning: mkbaselibs missing in build root, skipping baselibs
[ 1086s] ... saving statistics
[ 1086s] ... saving built packages
[ 1086s] DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3_amd64.changes
[ 1086s] DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3_amd64.buildinfo
[ 1086s] DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3.dsc
[ 1086s] DEBS/qemu-vanilla_4.1.1+git.99c5874a9b.orig.tar.gz
[ 1086s] DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3_amd64.deb
[ 1086s] DEBS/qemu-vanilla_4.1.1+git.99c5874a9b-3.diff.gz
[ 1086s] OTHER/_statistics
[ 1086s] 
[ 1086s] lamb60 finished "build qemu-vanilla.dsc" at Wed May 13 19:35:08 UTC 2020.
```
@jodh-intel  ping a ex ubuntu(deb) help would be nice

**Comment by jcvenegas** [comment]
```
[  169s]   CC      block/file-posix.o
[  169s] In file included from /usr/src/packages/BUILD/include/qemu/timer.h:4,
[  169s]                  from /usr/src/packages/BUILD/include/qemu/timed-average.h:29,
[  169s]                  from /usr/src/packages/BUILD/include/block/accounting.h:28,
[  169s]                  from /usr/src/packages/BUILD/include/block/block_int.h:27,
[  169s]                  from block/file-posix.c:30:
[  169s] /usr/include/linux/swab.h: In function '__swab':
[  169s] /usr/src/packages/BUILD/include/qemu/bitops.h:20:34: warning: "sizeof" is not defined, evaluates to 0 [-Wundef]
[  169s]  #define BITS_PER_LONG           (sizeof (unsigned long) * BITS_PER_BYTE)
[  169s]                                   ^~~~~~
[  169s] /usr/src/packages/BUILD/include/qemu/bitops.h:20:41: error: missing binary operator before token "("
[  169s]  #define BITS_PER_LONG           (sizeof (unsigned long) * BITS_PER_BYTE)
[  169s]                                          ^
[  169s] make[2]: *** [/usr/src/packages/BUILD/rules.mak:69: block/file-posix.o] Error 1
[  169s] make[2]: Leaving directory '/usr/src/packages/BUILD'
[  169s] make[1]: *** [debian/rules:11: override_dh_auto_build] Error 2
[  169s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[  169s] make: *** [debian/rules:5: build] Error 2
[  169s] dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
[  169s] ### VM INTERACTION START ###
[  172s] [  164.867436] sysrq: SysRq : Power Off
[  172s] [  164.873848] reboot: Power down
```

**Pull request merged**
