### PR TITLE
[2.0-dev] kernel: Enabling PTP clock support in kernel

### LINKED ISSUE #1103: Add PTP clock support in kernel for x86
This was accidently dropped when we moved to fragments. Add configs for time synchronization.

### PR DESCRIPTION
**Pull request by fidencio**
Allows time synchronization.

Fixes #1103

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
(cherry picked from commit c2023a217d57adbf3c74f62f35f962badcfb60ee)

### CODE REVIEW

**Review by jodh-intel — CHANGES_REQUESTED** [review]
Err - where did this `2.0-dev` branch come from? We already have https://github.com/kata-containers/kata-containers/tree/2.0-dev/tools/packaging so this is now very confusing...?!?

**Comment by fidencio** [comment]
@jodh-intel, trust me, I am confused as well.
Shall we get rid of the 2-0.dev branch entirely here?

**Comment by fidencio** [comment]
Closing this PR, as the patch is already pushed to `kata-containers/kata-containers`

**Pull request closed without merging**
