### PR TITLE
kernel: virtiofs: remove already applied patch

### PR DESCRIPTION
**Pull request by jcvenegas**
The virtios-dev tag changed recently to a new version:

Linux 5.8-rc4

This already include some patches, remove not needed patches.

Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

Fixes: #1095

### CODE REVIEW

**Comment by jcvenegas** [comment]
Hey Folks, I still having some build issue locally now are config issues, I am looking to it.
The first error I get is that the final config does not have `CONFIG_MEMCG_SWAP_ENABLED=y`. Seems that this was removed or moved in this version. I am looking where it is now or if only changed the name.

**Comment by GabyCT** [comment]
thanks @jcvenegas the issue is gone http://jenkins.katacontainers.io/job/kata-metrics-runtime-ubuntu-virtiofs-18-04-PR/6/console

**Comment by GabyCT** [comment]
@jcvenegas you need to bump the kernel config version please
```
10:40:16 ERROR: Please bump version in kernel/kata_config_version
```

**Comment by jcvenegas** [comment]
@amshinde so, the plan is to wait for  a proper tag, should I close this PR ?

**Comment by amshinde** [comment]
I dont think this is required any longer. Closing this @jcvenegas.

**Pull request closed without merging**
