### PR TITLE
obs: distros: enable SLE12-SP4

### PR DESCRIPTION
**Pull request by jcvenegas**
To allow test packages in azure.

Fixes: #661

### CODE REVIEW

**Comment by jcvenegas** [comment]
@GabyCT  I updated to 15 SP1 as suggested by @marcov, is that fine to you?

**Comment by GabyCT** [comment]
@marcov and @jcvenegas that image is not available on Azure

**Comment by jcvenegas** [comment]
@GabyCT  what is the latest version that azure  privides?

**Comment by GabyCT** [comment]
@jcvenegas SLES 12 SP4

**Comment by jcvenegas** [comment]
```
 174s] qemu-vanilla-data.x86_64: W: position-independent-executable-suggested /usr/share/qemu-vanilla/qemu/hppa-firmware.img
[  174s] qemu-vanilla-data.x86_64: W: position-independent-executable-suggested /usr/share/qemu-vanilla/qemu/openbios-ppc
[  174s] qemu-vanilla-data.x86_64: W: position-independent-executable-suggested /usr/share/qemu-vanilla/qemu/openbios-sparc32
[  174s] qemu-vanilla-data.x86_64: W: position-independent-executable-suggested /usr/share/qemu-vanilla/qemu/openbios-sparc64
[  174s] qemu-vanilla-data.x86_64: W: position-independent-executable-suggested /usr/share/qemu-vanilla/qemu/palcode-clipper
[  174s] qemu-vanilla-data.x86_64: W: position-independent-executable-suggested /usr/share/qemu-vanilla/qemu/u-boot.e500
[  174s] This executable should be position independent (all binaries should).  Check
[  174s] that it is built with -fPIE/-fpie in compiler flags and -pie in linker flags.
[  174s] 
[  174s] qemu-vanilla-data.x86_64: W: shared-lib-without-dependency-information /usr/share/qemu-vanilla/qemu/s390-ccw.img
[  174s] qemu-vanilla-data.x86_64: W: shared-lib-without-dependency-information /usr/share/qemu-vanilla/qemu/s390-netboot.img
[  174s] qemu-vanilla-data.x86_64: W: statically-linked-binary /usr/share/qemu-vanilla/qemu/hppa-firmware.img
[  174s] qemu-vanilla-data.x86_64: W: statically-linked-binary /usr/share/qemu-vanilla/qemu/openbios-ppc
[  174s] qemu-vanilla-data.x86_64: W: statically-linked-binary /usr/share/qemu-vanilla/qemu/openbios-sparc32
[  174s] qemu-vanilla-data.x86_64: W: statically-linked-binary /usr/share/qemu-vanilla/qemu/openbios-sparc64
[  174s] qemu-vanilla-data.x86_64: W: statically-linked-binary /usr/share/qemu-vanilla/qemu/palcode-clipper
[  174s] qemu-vanilla-data.x86_64: W: statically-linked-binary /usr/share/qemu-vanilla/qemu/u-boot.e500
[  174s] The package installs a statically linked binary or object file.  Usually this
[  174s] is a packaging bug. If not, contact your rpmlint distributor about this so
[  174s] that this error gets included in the exception file for rpmlint and will not
[  174s] be flagged as a packaging bug in the future (or add it to your local
[  174s] configuration if you installed rpmlint from the source tarball).
[  174s] 
[  174s] qemu-vanilla.x86_64: W: suse-filelist-empty packages without any files are discouraged in SUSE
[  174s] qemu-vanilla-bin.x86_64: E: invalid-license (Badness: 100000) BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1
[  174s] qemu-vanilla-data.x86_64: E: invalid-license (Badness: 100000) BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1
[  174s] qemu-vanilla.src: E: invalid-license (Badness: 100000) BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1
[  174s] qemu-vanilla.x86_64: E: invalid-license (Badness: 100000) BSD-2-Clause BSD-3-Clause GPL-2.0 GPL-2.0+ LGPL-2.0+ LGPL-2.1
[  174s] The specified license string is not recognized. Please refer to
[  174s] https://spdx.org/licenses/ for the list of known licenses and their exact
[  174s] spelling.
[  174s] 
[  174s] qemu-vanilla-bin.x86_64: E: summary-ended-with-dot (Badness: 20) C bin components for the qemu-vanilla package.
[  174s] qemu-vanilla-data.x86_64: E: summary-ended-with-dot (Badness: 20) C data components for the qemu-vanilla package.
[  174s] Summary ends with a dot.
[  174s] 
[  174s] qemu-vanilla-bin.x86_64: E: summary-not-capitalized (Badness: 20) C bin components for the qemu-vanilla package.
[  174s] qemu-vanilla-data.x86_64: E: summary-not-capitalized (Badness: 20) C data components for the qemu-vanilla package.
[  174s] Summary doesn't begin with a capital letter.
[  174s] 
[  174s] (none): E: badness 400080 exceeds threshold 1000, aborting.
[  174s] 4 packages and 0 specfiles checked; 8 errors, 44 warnings.
[  174s] 
[  174s] 
[  174s] lamb07 failed "build qemu-vanilla.spec" at Tue Aug  6 20:33:03 UTC 2019.
```
 SLE 15 defaults seems to be more strict :P

**Comment by amshinde** [comment]
@jcvenegas Any updates?

**Comment by jodh-intel** [comment]
Hi @jcvenegas - branch is conflicted.

**Comment by jcvenegas** [comment]
PR updated just updated SLE12 to SP4, SLE15 has some build issues that need to take a look. I am not planning to focus this days on update it so, lets just bump SLE12.

**Pull request merged**
