### PR TITLE
kernel: Install uncompressed kernel by Image instead of  vmlinux on arm64

### LINKED ISSUE #930: kernel: Install uncompressed kernel by Image instead of vmlinux on arm64
# Description of problem
    arm64 does not use vmlinux to boot, Image is used instead.
    
    Otherwise, kata can't boot from vmlinux.container
    
    Besides, given that firecracker only supports booting from Image,
    don't set vmlinux for firecracker target
# Expected result

arm64 kata container can boot up with uncompressed kernel image

# Actual result

failed to boot up

### PR DESCRIPTION
**Pull request by justin-he**
arm64 does not use vmlinux to boot, Image is used instead.

Otherwise, kata can't boot from vmlinux.container

Besides, given that firecracker only supports booting from Image,
don't set vmlinux for firecracker target

Fixes #930
Signed-off-by: Jia He <justin.he@arm.com>

### CODE REVIEW

**Comment by justin-he** [comment]
@kata-containers/builder

**Comment by jodh-intel** [comment]
Hi @justin-he - please can you update the branch as it is conflictedc.

**Comment by justin-he** [comment]
> Hi @justin-he - please can you update the branch as it is conflicted.

Sure, updated

**Comment by jodh-intel** [comment]
Thanks @justin-he.

/test

**Pull request merged**
