### PR TITLE
kata-deploy: add ACRN runtime to Docker configuration

### PR DESCRIPTION
**Pull request by gvancuts**
Add an ACRN runtime ('kata-acrn') to the Docker configuration (daemon.json)

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
@vijaydhanraj FYI

**Comment by devimc** [comment]
thanks @gvancuts - please fix the commit message https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format  

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

**Comment by gvancuts** [comment]
> thanks @gvancuts - please fix the commit message https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
> 
> https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

I have added a `Fixes:` line in my commit message. Was there something else that I needed to change? (I don't think so... but double-checking)

**Comment by krsna1729** [comment]
The formatting seems off for previous blocks. Also is there a closing bracket missing?

**Comment by gvancuts** [comment]
> The formatting seems off for previous blocks. Also is there a closing bracket missing?

Ouch... indeed... good catch. Should be fixed now.

Btw, is there an easy way I can test this on my system (sorry, not very familiar with how this all works together). Thanks!

**Comment by krsna1729** [comment]
https://github.com/kata-containers/packaging/tree/master/kata-deploy#docker-quick-start
you can mount your version of the script to test.
/cc @egernst

**Comment by gvancuts** [comment]
> https://github.com/kata-containers/packaging/tree/master/kata-deploy#docker-quick-start
> you can mount your version of the script to test.
> /cc @egernst

Done, I tested this using
```
$ sudo docker run -v /home/acrn/work/packaging/kata-deploy/scripts:/opt/kata-artifacts/scripts -v /opt/kata:/opt/kata -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd -v /etc/docker:/etc/docker -it katadocker/kata-deploy kata-deploy-docker install
```
And Docker could see and successfully use this new `kata-acrn` runtime (after a couple of minor tweaks, unrelated to this PR).

**Comment by gvancuts** [comment]
Just to make sure, since I'm not a regular contributor to this project, do I still need to do anything for this PR or it's on track?

**Pull request merged**
