### PR TITLE
config: add intel ixgbe/i40e SR-IOV support

### PR DESCRIPTION
**Pull request by Kvasscn**
enable intel ixgbe/i40e virtual functions in guest kernel configration.

Fixes: #733

Signed-off-by: zhanghj.lc <zhanghj.lc@inspur.com>

### CODE REVIEW

**Comment by egernst** [comment]
This is a straight forward patch, but I’m looking to get input from others in community. Users can create their own kernel with their specific hardware devices enabled today.

IMO, it’s wise to keep the reference kernel minimal, as most users won’t necessarily use SRIOV (maybe?), and may not use same NIC. Having said this, I don’t want to make usage painful for folks — do you think it’s reasonable to build a
Custom kernel for this? 

Or, would you like to see a much larger kernel available aside from the default which has many devices added (gpus, accelerators, NICs, etc)?

/cc @gnawux @jodh-intel @devimc @caoruidong @jongwu

**Comment by caoruidong** [comment]
@Kvasscn Do you have some statistics? Like kernel size and boot time compared to before.

**Comment by Kvasscn** [comment]
@caoruidong  I made a simple comparison,
the size of kernel without  ixgbe/i40e support:
vmlinux-4.19.65-51        22367656 Byte
vmlinuz-4.19.65-51          4578864 Byte
after enable  ixgbe/i40e support:
vmlinux-4.19.65-51        24712664 Byte
vmlinuz-4.19.65-51          4886064 Byte

**Comment by Kvasscn** [comment]
@egernst  I think it's convenient for the user who need SRIOV function，because there is no need to recompile the guest kernel, but as you said this increased  the kernel image size.
reference to this link https://github.com/kata-containers/documentation/blob/master/use-cases/using-SRIOV-and-kata.md, maybe some people use other types of adapters.

**Comment by amshinde** [comment]
@egernst I think we had this in our packaged kernel, before the fragmentation support was introduced.

**Pull request closed without merging**
