### PR TITLE
kernel/configs: enable swap extension (CONFIG_MEMCG_SWAP)

### LINKED ISSUE #103: Failed to run containers with memory constraints
```
Error response from daemon: Cannot update container 17db7e1d0245601bf328b7ce0eda47092c699ca5caecc5080b81ede4c50775a0: /usr/bin/kata-runtime did not terminate sucessfully: rpc error: code = Unknown desc = failed to write 188743680 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/docker/17db7e1d0245601bf328b7ce0eda47092c699ca5caecc5080b81ede4c50775a0/memory.limit_in_bytes: permission denied
: unknown
```

*failed to write 188743680 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/docker/17db7e1d0245601bf328b7ce0eda47092c699ca5caecc5080b81ede4c50775a0/memory.limit_in_bytes: permission denied*

### PR DESCRIPTION
**Pull request by devimc**
libcontainer limits the memory+swap usage by writing the limit at
/sys/fs/cgroup/memory/docker/$CONTID/memory.memsw.limit_in_bytes, this path
doesn't exist if CONFIG_MEMCG_SWAP and CONFIG_MEMCG_SWAP_ENABLED are not
enabled.

fixes #103

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
It somehow feels sort of wrong, enabling SWAP in the kernel when we have no swap devices in the container.
For reference, on all of my 'default out of the box' Ubuntu machines I believe, when I run host side something link `docker run --rm -ti -m 8G busybox sh` I get the warning:

`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted, Memory limited without swap.`
Which is implying to me either that the missing swap option didn't matter, or it was somehow limited by a different method.
afaict, the code that issues that warning is at:
https://github.com/moby/moby/blob/5fc12449d830ae9005138fb3d3782728fa8d137a/daemon/daemon_unix.go#L368

Does that bear relevance here?

**Comment by devimc** [comment]
@grahamwhaley  yes, I know it looks weird (enable swap when we don't have swap) but `libcontainer` specifies the maximum usage permitted for user memory plus swap space, I'll take a look to source code to see if it's possible to skip/disable it.

Take a look https://github.com/kata-containers/packaging/issues/103

**Comment by jodh-intel** [comment]
Any update on this @devimc? Also, why no updated to ppc64le's config?

/cc @nitkon.

**Comment by devimc** [comment]
@jodh-intel I'm waiting for review, ppc64le already has that config

**Comment by jodh-intel** [comment]
Ah - thiis'll be related to #8, #55, #56 then ;)

**Comment by devimc** [comment]
re-ping @kata-containers/packaging

**Comment by jodh-intel** [comment]
lgtm

/cc @nitkon.

**Comment by nitkon** [comment]
@jodh-intel : Its already enabled in ppc64le kernel config file and this patch changes only for x86 and arm.

**Comment by grahamwhaley** [comment]
I guess you did the research and didn't find a way to skip/disable it then @devimc ?

**Comment by devimc** [comment]
@grahamwhaley that's correct, we need these flags to honour memory constrains in the VM

**Comment by bergwolf** [comment]
@devimc What about arm config? It doesn't enable swap yet.

cc @kalyxin02 @Weichen81

**Comment by bergwolf** [comment]
oops, my bad, arm config is added there.

/lgtm

**Comment by bergwolf** [comment]
Let's merge it!

**Comment by Weichen81** [comment]
Thanks @devimc  ; )

**Pull request merged**
