### PR TITLE
release: Fix typos and organization issues

### PR DESCRIPTION
**Pull request by chavafg**
For better reading, re-orginize the `release/README.md`
and fix a typo in `runtime-release-notes.sh`.

Fixes: #769.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@jcvenegas the obs-packaging-ci keeps timing out... Any idea of how we can fix it?

**Comment by jcvenegas** [comment]
@chavafg yeah OBS is being quite slow this days - is the CI is failing after 5 hours of be waiting, I think that @flavio  could give us some feedback here.

**Comment by flavio** [comment]
> @chavafg yeah OBS is being quite slow this days - is the CI is failing after 5 hours of be waiting, I think that @flavio could give us some feedback here.

@rhafer could help with that. He's now going to help with kata at SUSE

**Comment by jodh-intel** [comment]
@flavio - great! Welcome @rhafer! :smile:

**Pull request merged**
