### PR TITLE
DNM: Revert "config: make virtio-fs part of standard kernel"

### PR DESCRIPTION
**Pull request by amshinde**
This reverts commit 3d2bb461eab80fe5a1f61ea96ced8c27451fb7e7.

This is a test to check if the recent increase in memory overhead
was caused by this.

Fixes: #666

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@GabyCT The metrics CI has passed with this. So virtiofs addition might be a possible candidate for the memory. But we havent run the metrics CI on this repo before as you mentioned. So we dont have a way to confirm the CI passed failed/passed before this change.
We need to have a metrics CI run before this change and after this change.

**Comment by GabyCT** [comment]
@amshinde I opened https://github.com/kata-containers/packaging/pull/1147 to test currently the repo

**Comment by fidencio** [comment]
As this is a do-not-merge one, let's close it as it won't make into the 1.13.0 final release.

**Pull request closed without merging**
