### PR TITLE
# Kata Containers 1.13.0-alpha0

### PR DESCRIPTION
**Pull request by egernst**
- github: Enable github actions
- add BPF related kernel config
- static-build: Use apply_patches.sh in qemu and kernel scripts

803f44b github: Enable github actions
74393d0 kernel: Add BPF related kernel configs
69d3c7e static-build: Use apply_patches.sh in qemu and kernel scripts
aa2d950 static-build/qemu: Common apply patches script

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @egernst

**Review by GabyCT — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Pull request merged**
