### PR TITLE
kata-deploy: add support for Cloud Hypervisor and remove nemu

### PR DESCRIPTION
**Pull request by chavafg**
- Add Cloud Hypervisor to kata-deploy.
- Remove nemu from kata-deploy.

Fixes: #808.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@egernst agree, updated.

**Comment by amshinde** [comment]
Rebased and pushed this for the packaging fix.

**Pull request merged**
