### PR TITLE
[1.11-stable] kernel: Enabling PTP clock support in kernel

### LINKED ISSUE #1103: Add PTP clock support in kernel for x86
This was accidently dropped when we moved to fragments. Add configs for time synchronization.

### PR DESCRIPTION
**Pull request by fidencio**
Allows time synchronization.

Fixes #1103

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
(cherry picked from commit c2023a217d57adbf3c74f62f35f962badcfb60ee)

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

**Review by wainersm — APPROVED** [review]

**Comment by fidencio** [comment]
```
12:31:52 not ok 2 initContainer with shared volume
12:31:52 # (in test file k8s-shared-volume.bats, line 44)
12:31:52 #   `kubectl exec "$pod_name" -c "$last_container" -- sh -c "$cmd"' failed
12:31:52 # INFO: k8s configured to use runtimeclass
12:31:52 # pod/initcontainer-shared-volume created
12:31:52 # pod/initcontainer-shared-volume condition met
12:31:52 # command terminated with exit code 1
12:31:52 # pod "initcontainer-shared-volume" deleted
12:31:52 Failed at 90: bats "${K8S_TEST_ENTRY}"
```

This seems weird and unrelated to this one. @GabyCT, @chavafg, was this reported already? If not, I'll file an issue and try to bisect it at some point soon.

**Review by amshinde — APPROVED** [review]

**Comment by chavafg** [comment]
@fidencio don't recall seen it before, but it is a good idea to open an issue to track it and debug if we see it again

**Pull request merged**
