### PR TITLE
v4.19.86: patch update for v4.19.86 on AArch64

### PR DESCRIPTION
**Pull request by Pennyzct**
Hi @egernst @gnawux 
Plz bump the version to v4.19.84, it will decrease the failed chunks. ;)
I've updated the patch, plz take a look~

### CODE REVIEW

**Comment by Pennyzct** [comment]
@devimc 
sorry, my neglect. 😋. already updated.

**Comment by devimc** [comment]
@Pennyzct CI is not happy, could you please take a look ?

```
1 out of 1 hunk FAILED -- saving rejects to file arch/arm64/include/asm/cpucaps.h.rej
patching file arch/arm64/include/asm/cpufeature.h
Hunk #3 FAILED at 533.
1 out of 3 hunks FAILED -- saving rejects to file arch/arm64/include/asm/cpufeature.h.rej
```

**Comment by devimc** [comment]
@Pennyzct , snap-stable (1.9) is failing, do you think that this patch should be backported ?

see https://launchpadlibrarian.net/454148156/buildlog_snap_ubuntu_bionic_arm64_stable_BUILDING.txt.gz

```
patching file include/uapi/linux/kvm.h
patching file virt/kvm/arm/arm.c
Hunk #4 succeeded at 514 (offset 11 lines).
Hunk #5 succeeded at 556 (offset 11 lines).
Hunk #6 succeeded at 1337 (offset 11 lines).
Hunk #7 succeeded at 1436 (offset 11 lines).
patching file virt/kvm/arm/mmu.c
Hunk #12 FAILED at 408.
Hunk #13 succeeded at 897 (offset 1 line).
Hunk #14 succeeded at 986 (offset 1 line).
Hunk #15 succeeded at 994 (offset 1 line).
Hunk #16 succeeded at 1003 (offset 1 line).
Hunk #17 succeeded at 1025 (offset 1 line).
Hunk #18 succeeded at 1207 (offset 1 line).
Hunk #19 succeeded at 1303 (offset 1 line).
Hunk #20 succeeded at 1337 (offset 1 line).
Hunk #21 succeeded at 1365 (offset 1 line).
Hunk #22 succeeded at 1379 (offset 1 line).
Hunk #23 succeeded at 1530 (offset 1 line).
Hunk #24 succeeded at 1773 (offset 1 line).
Hunk #25 succeeded at 2072 (offset 1 line).
1 out of 25 hunks FAILED -- saving rejects to file virt/kvm/arm/mmu.c.rej
patching file virt/kvm/arm/vgic/vgic-its.c
Hunk #9 succeeded at 2225 (offset 1 line).
Hunk #10 succeeded at 2297 (offset 1 line).
Hunk #11 succeeded at 2346 (offset 1 line).
patching file virt/kvm/arm/vgic/vgic-kvm-device.c
patching file virt/kvm/arm/vgic/vgic-mmio-v3.c
Failed to run 'override-build': Exit code was 1.
```

**Pull request merged**
