### PR TITLE
config: enable printk_time for arm64.

### PR DESCRIPTION
**Pull request by jongwu**
As no printk time enabled for arm64, printk and dmesg will show
without timestamp.
This patch enables printk_time in kernel for arm64.

Fixes: #875
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
@jodh-intel  @grahamwhaley  @devimc @Pennyzct

### CODE REVIEW

**Comment by jongwu** [comment]
seems the failure is nothing to do with this commit. @grahamwhaley

**Comment by grahamwhaley** [comment]
@jongwu - from the Ubuntu 18.04 CI Jenkins logs... (you have to look back up a little from the end of the log to find the real reasons for failure....):

```
09:51:41 kernel/configs/arm64_kata_kvm_4.19.x
09:51:41 Kernel directory has changes check kernel/kata_config_version changed
09:51:41 ERROR: Please bump version in kernel/kata_config_version
09:51:41 Makefile:24: recipe for target 'test' failed
09:51:41 make: *** [test] Error 1
```

So, yes, you do need to bump the kernel config version file ;-)

**Comment by jongwu** [comment]
thanks @grahamwhaley

**Comment by jongwu** [comment]
@grahamwhaley  @devimc crio test fail
`00:32:30 #   `[[ "$output" =~ "command timed out" ]]' failed
00:32:30 # time="2019-12-12T16:32:00Z" level=error msg="File descriptor 3 (pipe:[646976]) leaked on pvdisplay invocation. Parent PID 53073: /tmp/jenkins/workspace/kata-con\nFile descriptor 6 (/dev/mapper/control) leaked on pvdisplay invocation. Parent PID 53073: /tmp/jenkins/workspace/kata-con\n  Failed to find physical volume \"/dev/sdb\".\n" error="exit status 5"`

**Comment by grahamwhaley** [comment]
I wonder if this is the same or related to the cri-o tests instability/failure that @amshinde is tracking/testing over on https://github.com/kata-containers/tests/pull/2168 ?

**Comment by jongwu** [comment]
help trigger obs ci, thanks, @tedyu

**Comment by jongwu** [comment]
obs ci has stuck for 2 days @devimc

**Comment by jongwu** [comment]
it's strange that obs ci does not work. @devimc

**Comment by devimc** [comment]
haha you broke it @jongwu , let's restart it again

/AzurePipelines restart

**Comment by devimc** [comment]
obs-packaging-ci stuck again

/AzurePipelines run

cc @jcvenegas

**Comment by grahamwhaley** [comment]
@devimc - to trigger AzurePipelines, that comment must be the only thing in the comment field... nothing else...

**Comment by devimc** [comment]
thanks @grahamwhaley  :sweat_smile:

**Comment by grahamwhaley** [comment]
OBS/Azure looked like it had gotten stuck or failed to update progress again - nudged, again.

**Pull request merged**
