### PR TITLE
kernel: Move to virtiofs kernel tag

### PR DESCRIPTION
**Pull request by jcvenegas**
virtiofs-dev is a branch, now there is a tag
based in kernel 5.6 move patches to use the tag name.

Depends-on: github.com/kata-containers/runtime#2843

Fixes: #1095

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@jcvenegas we need to bump kata_config_version here

**Comment by amshinde** [comment]
@jcvenegas we need to bump kata_config_version here

**Comment by likebreath** [comment]
@jcvenegas To have a reference of our discuss over slack:

It looks like we are only carrying one custom kernel path, a.k.a fix race condition for virtio_vsock. Does it mean the other custom kernel patches we had are already in the updated kernel (e.g. the patch to enable evged)? The previous commits have three custom kernel patches: https://github.com/kata-containers/packaging/commit/8abf130d29c383781ad0588db505b76f87583fda.

**Pull request merged**
