### PR TITLE
kernel: fix open-unlink-ftruncate bug from 9p

### PR DESCRIPTION
**Pull request by jongwu**
Now, this bug has fixed in kernel side, see
https://lkml.org/lkml/2020/7/3/257 and the patch
has merged into 5.9, so port this patch into kata.
But qemu side is not ready, so it won't work for now.

Fixes: #1137
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

@jodh-intel @devimc  @bergwolf

### CODE REVIEW

**Comment by jongwu** [comment]
hi @jodh-intel @GabyCT, any comments?

**Review by jodh-intel — APPROVED** [review]
\o/ Thanks @jongwu!

lgtm

**Review by GabyCT — APPROVED** [review]

**Comment by jodh-intel** [comment]
Thanks @jongwu - does this need porting to https://github.com/kata-containers/kata-containers/tree/2.0-dev/tools/packaging?

**Pull request merged**
