### PR TITLE
ci: Add intial pipeline to test OBS package generation

### PR DESCRIPTION
**Pull request by jcvenegas**
Add simple yaml definition to run job in azure pipelines.

Fixes: #480

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@jcvenegas Interesting.
Can we have a few more details of how this infra is set up and maintained, and what the final goal is etc. pls? such as:

- What sort of Azure account is this using - is it the free for open source one, or a paid by Kata one for instance?
- Are the users who can trigger runs whitelisted (it looks like that is a fairly manual process at the Azure config end, and cannot be done in the YAML afaict)
- What is the ultimate goal for this pipe?

**Comment by grahamwhaley** [comment]
Ah, I see some questions already answered over at https://github.com/kata-containers/packaging/pull/595#issuecomment-505130212 - thx!

**Comment by jcvenegas** [comment]
> Can we have a few more details of how this infra is set up and maintained, and what the final goal is etc. pls? such as:
> 
> * What sort of Azure account is this using - is it the free for open source one, or a paid by Kata one for instance?
Yeah it is an open source free usage account.



> * Are the users who can trigger runs whitelisted (it looks like that is a fairly manual process at the Azure config end, and cannot be done in the YAML afaict)

Yeah,  I just enabled, I need to find if is there a way to get people doing this form the kata organization. I want it in this way because I want to use some secrets so we need to prevent to wait until we ack to run the test


> * What is the ultimate goal for this pipe?

I want to make sure we are able to create packages, in the last months packages are being broken quite a lot. 
So create a OBS packages based on kata head -> probably also add a validation to make sure it can install the packages and is well configured looking to kata-runtime kata-env.

**Pull request merged**
