### PR TITLE
docs: kernel configs: minor improvements

### PR DESCRIPTION
**Pull request by grahamwhaley**
The documentation around the use, layout and modification of the
kernel configs, especially the fragments, was a bit lacking. Add
some minor updates.

Fixes: #1054

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Rather a worrying error reported in the failing CI's:

```
Copy containers policy from CRI-O repo to /etc/containers
/tmp/jenkins/workspace/kata-containers-packaging-ubuntu-18-04-snap-PR/go/src/github.com/kata-containers/tests
Installing CRI Tools
fatal: Not a valid commit name 0f1226b99685f95e83c94dc6668b6452df5056db
Install runc for CRI-O
```

**Comment by grahamwhaley** [comment]
kernel version file bump added.
/test-ubuntu

**Comment by grahamwhaley** [comment]
/test-snap
looked like spurious net connection/hub failure.

**Comment by grahamwhaley** [comment]
rebased and pushed
/test-ubuntu
/test-snap

**Comment by amshinde** [comment]
Rebased and pushed.
/test-ubuntu
/test-snap

**Comment by jodh-intel** [comment]
Restarted snap CI which timed out.

**Pull request merged**
