### PR TITLE
obs-packaging: Add Eric Auger's latest PCDIMM/NVDIMM patches

### PR DESCRIPTION
**Pull request by teawater**
Add Eric Auger's latest PCDIMM/NVDIMM patches for supporting nvdimm
on aarch64.

Fixes: #270

Signed-off-by: Hui Zhu <teawater@hyper.sh>

### CODE REVIEW

**Comment by jodh-intel** [comment]
I'm afraid I'm confused - this PR adds a patch but doesn't appear to make use of it in the packaging?

**Comment by devimc** [comment]
:worried:  I'd prefer to update the whole kernel

**Comment by teawater** [comment]
@jodh-intel It is used by https://github.com/kata-containers/tests/pull/962

**Comment by bergwolf** [comment]
@jodh-intel There is just no aarch64 obs yet. This is supposed to be used for testing and verification first and we can bring in aarch64 packages step by step.

**Comment by jodh-intel** [comment]
@bergwolf - ack.

lgtm

**Comment by gnawux** [comment]
LGTM

**Comment by gnawux** [comment]
Thanks @teawater

**Pull request merged**
