### PR TITLE
Memory hotplug 4.19

### PR DESCRIPTION
**Pull request by jongwu**
kernel: Enable memory hotplug(add) for arm64

    This patch is update version for [1] as kernel
    upgrad to v4.19.
    It derives from [2] which has accept by kernel
    community after v4.20. Modifacation has been done
    to make it be able to enable memory hotplug using
    probe method as it originally aims to using acpi.
    Also some corresponding configurations in kernel
    config are opened.

    [1] https://github.com/kata-containers/packaging/
    commit/e654dbd8367371c1b34776445a402d3c90f0dc66
    [2] https://git.kernel.org/pub/scm/linux/kernel/
    git/torvalds/linux.git/commit/
    ?id=4ab215061554ae2a4b78744a5dd3b3c6639f16a7

    Signed-off-by: Jianyong Wu  <jianyong.wu@arm.com>
@jodh-intel @Pennyzct @bergwolf @teawater

### CODE REVIEW

**Comment by jongwu** [comment]
@devimc thanks. done.

**Comment by devimc** [comment]
@jongwu please bump the version again

**Comment by jongwu** [comment]
@devimc ok, done

**Pull request merged**
