### PR TITLE
kernel: enable SHPC

### LINKED ISSUE #185: Hotplugged devices are not detected in q35
we need SHPC support

### PR DESCRIPTION
**Pull request by devimc**
SHPC is need to support hotplug in q35

fixes #185

cc @sboeuf @amshinde 

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@devimc ERROR: Please bump version in kernel/kata_config_version

**Comment by sboeuf** [comment]
@bergwolf here is the fix that you need if you want to make network hotplug working with q35 machine type.

**Comment by jodh-intel** [comment]
lgtm

The arm64 kernel config already has this, but s390 and ppc64le don't.

/cc @alicefr, @nitkon.

**Comment by devimc** [comment]
all green :)

**Pull request merged**
