### PR TITLE
kata-deploy: add or overwrite runtimes in containerd config

### PR DESCRIPTION
**Pull request by wilsonianb**
Match indented CRI-O config fields.
Fix CRI-O qemu virtiofs runtime_path.

Fixes: #802

Signed-off-by: Brandon Wilson <brandon@coil.com>

Replaces #805
Overwriting may fail if there's whitespace in the existing table name or if the target key/value pair doesn't appear in the first line after the table name (https://github.com/kata-containers/packaging/issues/802#issuecomment-553739129)

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Decided to chase this obs-CI fail a little. In the logs I found:

```
2019-11-16T16:05:12.8532664Z find . -maxdepth 2 -type d -name '*home:katacontainers*' -prune -exec sudo rm -rf {} \;
2019-11-16T16:05:12.8644252Z ~/work/1/s/obs-packaging/kata-containers-image ~/work/1/s/obs-packaging
2019-11-16T16:05:12.8645392Z Building image
2019-11-16T16:05:12.8852976Z /home/vsts/work/1/s/obs-packaging/scripts/../versions.txt: line 23: Not: command not found
2019-11-16T16:05:12.9101009Z 
2019-11-16T16:05:12.9190447Z ##[error]Bash exited with code '127'.
2019-11-16T16:05:12.9201258Z ##[section]Finishing: Request build to OBS
```

/cc @jcvenegas @chavafg @egernst

**Comment by jodh-intel** [comment]
Packaging CI is failing with:

```
~/work/1/s/obs-packaging/kata-containers-image ~/work/1/s/obs-packaging
Building image
/home/vsts/work/1/s/obs-packaging/scripts/../versions.txt: line 23: Not: command not found
```

**Comment by amshinde** [comment]
@jodh-intel This PR should fix the above error : https://github.com/kata-containers/packaging/pull/804

**Comment by amshinde** [comment]
This may be need a rebase. @wilsonianb Can you rebase your changes on top of latest master?

**Comment by wilsonianb** [comment]
rebased

**Comment by amshinde** [comment]
@wilsonianb Can I ask you to rebase this once more to resolve the merge conflicts?

**Comment by wilsonianb** [comment]
rebased

**Pull request merged**
