### PR TITLE
kernel: backport Linux upstream vhost_net fix

### PR DESCRIPTION
**Pull request by marcov**
Backport the Linux upstream patch 060423bfdee3:
  vhost: make sure log_num < in_num

Fixes: #723

Signed-off-by: Marco Vedovati <mvedovati@suse.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@marcov can you please bump the kata kernel version: 
```
07:28:29 Kernel directory has changes check kernel/kata_config_version changed
07:28:29 ERROR: Please bump version in kernel/kata_config_version
07:28:29 Makefile:24: recipe for target 'test' failed
```

**Comment by marcov** [comment]
oops, thanks @chavafg for reminding me.

/test

**Comment by egernst** [comment]
This has landed in 4.19.73 - let's grab from there instead!

**Comment by marcov** [comment]
Yea, closing this in favor of https://github.com/kata-containers/runtime/commit/82c277384be1061cca2cda3494a60cee5f3fa196

**Pull request closed without merging**
