### PR TITLE
qemu/default-configs: update default-config for QEMU 5

### LINKED ISSUE #1135: snap: couldn't build QEMU 5 in launchpad
can't build the snap in launchpad, unable to build QEMU 5

```
    CONFIG_IPMI=n
    select IPMI if PCI_IPMI_KCS
Traceback (most recent call last):
  File "/build/kata-containers/parts/qemu/build/qemu-repo/scripts/minikconf.py", line 703, in <module>
    config = data.compute_config()
  File "/build/kata-containers/parts/qemu/build/qemu-repo/scripts/minikconf.py", line 253, in compute_config
    clause.process()
  File "/build/kata-containers/parts/qemu/build/qemu-repo/scripts/minikconf.py", line 200, in process
    self.dest.set_value(True, self)
  File "/build/kata-containers/parts/qemu/build/qemu-repo/scripts/minikconf.py", line 118, in set_value
    raise KconfigDataError('contradiction between clauses when setting %s' % self)
__main__.KconfigDataError: contradiction between clauses when setting IPMI
```

### PR DESCRIPTION
**Pull request by devimc**
Disable the following IPMI configs, since they are not needed
for kata containers and fixes the snap job in launchpad

CONFIG_PCI_IPMI_KCS
CONFIG_PCI_IPMI_BT
CONFIG_IPMI_SSIF

fixes #1135

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
forward port here https://github.com/kata-containers/kata-containers/pull/653

**Comment by devimc** [comment]
@cmaf @likebreath @fidencio @GabyCT  please take a look

**Review by cmaf — APPROVED** [review]
@devimc lgtm

**Review by likebreath — APPROVED** [review]

**Pull request merged**
