### PR TITLE
README: Fix a typo in Kernel Readme

### PR DESCRIPTION
**Pull request by nitkon**
Fix a typo

Fixes:  #583

Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Ha ha ha - fell foul of the CI though - we could make that smarter maybe:

```
kernel/README.md
Kernel directory has changes check kernel/kata_config_version changed
ERROR: Please bump version in kernel/kata_config_version
Makefile:24: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by jcvenegas** [comment]
@nitkon  please bump the  file.  :) 
```
Kernel directory has changes check kernel/kata_config_version changed
ERROR: Please bump version in kernel/kata_config_version
Makefile:24: recipe for target 'test' failed
```

**Comment by jodh-intel** [comment]
@jcvenegas - the new `pkgsync-pipeline` check is failing:

```
Using context: pkgsync-pipeline
Setting status of 3c246365b9f147c2c3859bf7dc08961e5eb1059e to FAILURE with url http://jenkins.katacontainers.io/job/pkgsync-pipeline/19/ and message: 'Build finished. '
Using context: pkgsync-pipeline
java.io.FileNotFoundException
```

**Comment by jodh-intel** [comment]
Snap build is going to fail due to the patch not applying but I've restarted the 18.04 CI which _should_ now pass as the `kernel_version` file has been updated.

**Comment by GabyCT** [comment]
@nitkon could you please rebase this PR? thanks

**Comment by nitkon** [comment]
All green except `obs-packaging-ci`. How do we trigger it?

**Comment by grahamwhaley** [comment]
/AzurePipelines run
maybe....

**Comment by grahamwhaley** [comment]
sigh, I guess Azure pipelines regexp takes the complete comment then @jcvenegas ??

**Comment by nitkon** [comment]
Thnx @grahamwhaley. Finally all green!

**Pull request merged**
