### PR TITLE
Revert: "Revert "kernel: update guest kernel to 4.19.8 on aarch64 ""

### PR DESCRIPTION
**Pull request by jcvenegas**
This reverts commit 0a5b5adbfbc56ad8fb199b67ffa90286ba1636c9.

Now the kernel to build is 4.19

Fixes: #301

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
CI failing:

```
Setup a default kernel
/tmp/jenkins/workspace/kata-containers-packaging-ubuntu-16-04-PR/go/src/github.com/kata-containers/packaging/.ci/../Makefile:36: recipe for target 'test-build-kernel' failed
make[1]: *** [test-build-kernel] Error 1
```

**Comment by jodh-intel** [comment]
CI still failing:

```
patching file virt/kvm/arm/vgic/vgic-mmio-v3.c
Hunk #1 succeeded at 326 (offset -38 lines).
Hunk #2 succeeded at 343 (offset -38 lines).
Error:
line: 57
Last saved output:
Overview:

	Build a kernel for Kata Containers
	
Description: This script is the *ONLY* to build a kernel for development.


Usage:

	build-kernel.sh [options] <command> <argument>

Commands:

- setup

- build

- install

Options:

	-c <path>: Path to config file to build a the kernel
	-h       : Display this help.
	-k <path>: Path to kernel to build
	-p <path>: Path to a directory with patches to apply to kernel.
	-v       : Kernel version to use if kernel path not provided.
/tmp/jenkins/workspace/kata-containers-packaging-ubuntu-16-04-PR/go/src/github.com/kata-containers/packaging/.ci/../Makefile:36: recipe for target 'test-build-kernel' failed
```

**Comment by jcvenegas** [comment]
Seems that now fail as expected @jodh-intel 

```
Hunk #24 succeeded at 1552 (offset -220 lines).
Hunk #25 succeeded at 1852 (offset -219 lines).
4 out of 25 hunks FAILED -- saving rejects to file virt/kvm/arm/mmu.c.rej
patching file virt/kvm/arm/vgic/vgic-its.c
Hunk #1 succeeded at 233 (offset -8 lines).
Hunk #2 succeeded at 696 (offset -56 lines).
```

This PR adds a patch that is for 4.19, but the kernel that is being tested in 4.14, when a new PR for 4.19 is done will need to add a depends-on.

**Comment by Pennyzct** [comment]
Hi~ @jcvenegas thanks for the re-reverting. should we wait for this [PR](https://github.com/kata-containers/runtime/pull/1111) landed firstly?

**Comment by jodh-intel** [comment]
Added dnm due to dependency on https://github.com/kata-containers/runtime/pull/1111.

**Comment by caoruidong** [comment]
ping @jcvenegas

**Comment by sboeuf** [comment]
@jcvenegas can you rework this PR so that we keep 4.14.x along with 4.19.x? This will get this PR to pass first, and then we will be able to move to 4.19 for the whole CI.

**Pull request closed without merging**
