### PR TITLE
qemu: update qemu default config for arm

### PR DESCRIPTION
**Pull request by jongwu**
As qemu has upgrade to 5.1 on arm, default config file should
update accordingly.

Fixes: #1157
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

@jodh-intel @devimc

### CODE REVIEW

**Comment by devimc** [comment]
@jongwu  does this need forward-port ?

**Comment by jongwu** [comment]
@devimc - yeah, it need to port-forward this to packaging:2.0 and kata-containers:2.0. I will do it later.

**Comment by jongwu** [comment]
@devimc - help trigger ARM ci, thanks

**Review by GabyCT — APPROVED** [review]

**Comment by jongwu** [comment]
Hi @devimc @jodh-intel , help trigger ARM CI, thanks.

**Comment by jodh-intel** [comment]
/test-arm

Hi @jongwu - I've added you to this repo and the main 2.x one so that you should be able to trigger builds from now on ;)

**Comment by jongwu** [comment]
Thanks @jodh-intel 😄

**Comment by jongwu** [comment]
can we merge this @jodh-intel @devimc ?

**Pull request merged**
