### PR TITLE
obs: Add Fedora 31 for obs packaging

### LINKED ISSUE #775: obs: build packages for fedora 31
Now that Fedora 31 is available, start building packages for it.

### PR DESCRIPTION
**Pull request by GabyCT**
This adds fedora 31 for obs packaging.

Fixes #775

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
curious -- Fedora 31 has Kata support.  Do we need to create packages?  Should we just work on fixing/helping those?

**Comment by grahamwhaley** [comment]
> curious -- Fedora 31 has Kata support. Do we need to create packages? Should we just work on fixing/helping those?

Good question @egernst - it might depend on what cadence/update policy Fedora have for kata packages - if they are 'fixed to a stable', maybe kata upstream could provide leading edge - but, yes, ideally once kata is packaged with a distro, we should support them and let that be the primary source for installation. If somebody needs real bleeding edge, they could always go the from-source path.

**Comment by grahamwhaley** [comment]
Marking as rfc until it's discussed some more.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/packaging/issues/6.

Can you comment on this @lsm5?

**Comment by jodh-intel** [comment]
@lsm5i, @c3d, @fatherlinux, @mrguitar - could one of you comment on this please?

**Comment by jodh-intel** [comment]
typo: meant to ping @lsm5 there too ;)

**Comment by c3d** [comment]
I personally don't mind having Fedora31 built in obs, but I have no idea about what the project's policy is. Maybe it will cause confusion to have two packages for the same distro?

**Comment by GabyCT** [comment]
Closing this issue as we have a testing for Fedora 31 distro packages

**Comment by c3d** [comment]
@GabyCT  What would be the approach to test Fedora 32? Should I update this test, or should the test exist both for F31 and F32?

**Pull request closed without merging**
