### PR TITLE
kernel: build: Use local kernel version.

### PR DESCRIPTION
**Pull request by jcvenegas**
If the runtime repository is already cloned get version from it,
else keep getting from github.

Fixes: #299

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Lets wait to merge, https://github.com/kata-containers/tests/pull/1032 first.

**Comment by jcvenegas** [comment]
Finally testing again the kernel PRs, 
```
Check Changes in kernel ...
```

**Comment by jodh-intel** [comment]
CI failing:

```
Setup a default again wont download again the kernel
/tmp/jenkins/workspace/kata-containers-packaging-ubuntu-16-04-PR/go/src/github.com/kata-containers/packaging/.ci/../Makefile:36: recipe for target 'test-build-kernel' failed
make[1]: *** [test-build-kernel] Error 1
```

**Comment by devimc** [comment]
Thanks @jcvenegas 
lgtm

**Pull request merged**
