### PR TITLE
obs: repo: allow define multiple obs projects.

### PR DESCRIPTION
**Pull request by jcvenegas**
Enable EPEL repository for RHEL

Fixes: #485

### CODE REVIEW

**Comment by jcvenegas** [comment]
@marcov I am not sure if I am missing something, my testing branch it is still failing.

I still see that an old gcc is installed.

https://build.opensuse.org/package/show/home:katacontainers:releases:x86_64:alpha/runtime
https://build.opensuse.org/projects/home:katacontainers:releases:x86_64:alpha/meta

**Comment by marcov** [comment]
@jcvenegas I think you did right with the meta. 
I actually think I just validated that  you can build the runtime on RHEL with a more recent version of binutils (2.27 if I am right) :confused: 

But we still miss the part of making OBS pull a more recent version of binutils.

**Comment by amshinde** [comment]
@jcvenegas Can you rebase?

**Comment by egernst** [comment]
@jcvenegas next steps for this PR?

**Comment by jcvenegas** [comment]
It was to verify if redhat can can build with epel repos, but it failed the PR still make sense if in the future we want to add  more than one repo, @marcov  @jodh-intel  you still see value to add this functionality ?

**Comment by dagrh** [comment]
I wouldn't worry that much about building on old-RHEL with EPEL.
It's better to spend the time on the CentOS build; the packages work on RHEL as far as I can tell and it's a much closer to how we actually build on RHEL.
Then the only thing needed is to tweak the scripted install to use the CentOS RPMs on RHEL.

**Comment by marcov** [comment]
@jcvenegas I would follow what's proposed by @dagrh

**Comment by jcvenegas** [comment]
Closing based on feedback

**Pull request closed without merging**
