### PR TITLE
release: Remove release docs

### LINKED ISSUE #960: Remove release documentation
As part of https://github.com/kata-containers/documentation/issues/600, we want all docs related to release process to reside in the documentation repo.

### PR DESCRIPTION
**Pull request by amshinde**
All the release docs have been added to the documentation repo.

Fixes #960

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
Merge this after https://github.com/kata-containers/documentation/pull/605

**Comment by amshinde** [comment]
@jcvenegas Can we remove this wiki as well now : https://github.com/kata-containers/packaging/wiki/Release-process

**Comment by jcvenegas** [comment]
wiki deleted

**Comment by jodh-intel** [comment]
That's a scary comment to read out of context first thing in the morning @jcvenegas :smile:

**Pull request merged**
